// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjeX5rr2TPRuR9AGFdyvJbRYzka0CoGZY',
    appId: '1:145834077795:web:9055af6cd5b45fa2b69256',
    messagingSenderId: '145834077795',
    projectId: 'chigusai63',
    authDomain: 'chigusai63.firebaseapp.com',
    storageBucket: 'chigusai63.firebasestorage.app',
    measurementId: 'G-BXJHJ3FQ09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-NSVrNkoEz4FZLZgSdEd7HQKRP91iyyc',
    appId: '1:145834077795:android:ddbb8457a2c9df00b69256',
    messagingSenderId: '145834077795',
    projectId: 'chigusai63',
    storageBucket: 'chigusai63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiGgotlSDyhCQbIlCz7JYUmNP2qdHV2-o',
    appId: '1:145834077795:ios:b50d7df3f794149fb69256',
    messagingSenderId: '145834077795',
    projectId: 'chigusai63',
    storageBucket: 'chigusai63.firebasestorage.app',
    iosBundleId: 'com.example.chigusaApp63New',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiGgotlSDyhCQbIlCz7JYUmNP2qdHV2-o',
    appId: '1:145834077795:ios:b50d7df3f794149fb69256',
    messagingSenderId: '145834077795',
    projectId: 'chigusai63',
    storageBucket: 'chigusai63.firebasestorage.app',
    iosBundleId: 'com.example.chigusaApp63New',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjeX5rr2TPRuR9AGFdyvJbRYzka0CoGZY',
    appId: '1:145834077795:web:6f2f63ec74ee583db69256',
    messagingSenderId: '145834077795',
    projectId: 'chigusai63',
    authDomain: 'chigusai63.firebaseapp.com',
    storageBucket: 'chigusai63.firebasestorage.app',
    measurementId: 'G-PGD9X17PHE',
  );

}